<?php
return [ 
	
		'TB_1' => 'success' ,
		'TB_2' => 'token' ,
		'TB_3' => 'message' ,
		'TB_4' => 'html' ,
		'TB_5' => 'token' ,
		'TB_6' => 'publicaciones' ,
		'TB_7' => 'publicar' ,
		'TB_8' => 'inicial' ,
		'TB_9' => 'final' ,
		'TB_10' => 'titulo' ,
		'TB_11' => 'hora_final' ,
		'TB_12' => 'area' ,
		'TB_13' => 'archivos' ,
		'TB_14' => 'publicacion' ,
		'TB_15' => 'areas' ,
		'TB_16' => 'archivo' ,
		'TB_17' => 'tarea_id' ,
		'TB_18' => 'tipo_documento' ,
		'TB_19' => 'id' ,
		'TB_20' => 'id_usuario' ,
		'TB_21' => 'email' ,
		'TB_22' => 'tipo_usuario' ,
		'TB_23' => 'descripcion' ,
		'TB_24' => 'fecha_inicial' ,
		'TB_25' => 'fecha_final' ,
		'TB_26' => 'valor' ,
		'TB_27' => 'estado' ,
		'TB_28' => 'users' ,
		'TB_29' => 'alias' ,
		'TB_30' => 'password' ,
		'TB_31' => 'titulo_tarea' ,
		'TB_32' => 'area_id' ,
		'TB_33' => 'publicacion_id' ,
		'TB_34' => 'estado_entrega' ,
		'TB_35' => 'Su publicación se ha actualizado exitósamente' ,
		'TB_36' => 'Su publicación se ha eliminado exitósamente' ,
		'TB_37' => 'Los archivos fueron eliminados exitósamente' ,
		'TB_38' => 'Los archivos fueron agregados a la publicacion' 
];
